### ISSUE TITLE
There is no meaningful data on error, stacktrace.

### ISSUE THREAD

**Issue by hyunahOh** [carloscuesta/react-native-error-boundary#315]
There is no meaningful data on error, stacktrace, because in the release version, the function or component names changed. How can I get the real names from error message?

```{"componentStack":"\n    in F\n    in RCTView\n    in Unknown\n    in RCTScrollView\n    in C\n    in ScrollView\n    in Unknown\n    in RCTView\n    in Unknown\n    in Unknown\n    in v\n    in j\n    in C\n    in RCTView\n    in Unknown\n    in Unknown\n    in i\n    in RCTView\n    in Unknown\n    in RCTScrollView\n    in AndroidSwipeRefreshLayout\n    in _\n    in C\n    in ScrollView\n    in Unknown\n    in h\n    in b\n    in L\n    in Unknown\n    in P\n    in Unknown\n    in Unknown\n    in RCTView\n    in Unknown\n    in Unknown\n    in RCTView\n    in Unknown\n    in Unknown\n    in R\n    in n\n    in u\n    in Unknown\n    in Unknown\n    in Unknown\n    in Unknown\n    in RCTView\n    in Unknown\n    in E\n    in q\n    in RNSScreen\n    in P\n    in Unknown\n    in b\n    in P\n    in RNSScreenStack\n    in ScreenStack\n    in b\n    in RCTView\n    in Unknown\n    in v\n    in Unknown\n    in Unknown\n    in RCTView\n    in Unknown\n    in RCTView\n    in Unknown\n    in M\n    in S\n    in Unknown\n    in Unknown\n    in Unknown\n    in RCTView\n    in Unknown\n    in RCTView\n    in Unknown\n    in Unknown\n    in Unknown\n    in q\n    in RNSScreen\n    in P\n    in Unknown\n    in b\n    in Unknown\n    in RNSScreenContainer\n    in ScreenContainer\n    in Unknown\n    in RCTView\n    in Unknown\n    in v\n    in Unknown\n    in Unknown\n    in Unknown\n    in j\n    in Unknown\n    in Unknown\n    in Unknown\n    in RCTView\n    in Unknown\n    in E\n    in q\n    in RNSScreen\n    in P\n    in Unknown\n    in b\n    in P\n    in RNSScreenStack\n    in ScreenStack\n    in b\n    in RCTView\n    in Unknown\n    in v\n    in Unknown\n    in Unknown\n    in N\n    in Unknown\n    in Unknown\n    in Unknown\n    in Unknown\n    in f\n    in RNCSafeAreaProvider\n    in Unknown\n    in c\n    in RCTView\n    in Unknown\n    in Portal.Host\n    in b\n    in v\n    in s\n    in Unknown\n    in W\n    in c\n    in _\n    in RCTView\n    in Unknown\n    in RCTView\n    in Unknown\n    in E","isComponentError":true}```

**Comment by carloscuesta** [comment]
Hey! 

All the applications that are compiled and in release mode, will throw obfuscated errors like the one you shared on this issue. By design this is the default behaviour of react-native. What the library is doing is just acting like a proxy, so essentially all the errors that catched by the `ErrorBoundary` are forwarded to a callback so you can track this errors back.

If you want to have human readable errors in production, you'll have to match the errors with the source maps of your application.

[Sourcemaps](https://reactnative.dev/docs/symbolication) are debug files that are created every time you compile this application, they contain references to the code non obfuscated code, so you can match errors with your codebase properly.

Not sure about the error monitoring platform that you use, but all of the ones I know provide source maps support for react-native:

- https://docs.bugsnag.com/platforms/javascript/source-maps/
- https://docs.sentry.io/platforms/react-native/sourcemaps/
- https://docs.rollbar.com/docs/react-native

Let me know if you have other questions! 😊

**Comment by hyunahOh** [comment]
@carloscuesta This is really amazing answer. Thank you.
