### ISSUE TITLE
Remove FallbackComponent

### ISSUE THREAD

**Issue by ThushalIntervest** [carloscuesta/react-native-error-boundary#333]
How to Remove the FallbackComponent? can you please explain how to remove it? I didn't find a solution in this repo.

**Comment by carloscuesta** [comment]
Hey! 

I would not recommend removing the `FallbackComponent`, since it's there for a reason, whenever you have an error you want to explain to the user that an error happened.

However, as mentioned [in the docs](https://github.com/carloscuesta/react-native-error-boundary#custom-fallback-component):

> <img width="867" alt="Screenshot 2022-07-15 at 15 57 24" src="https://user-images.githubusercontent.com/7629661/179238008-06a2fb45-43a2-492a-94d7-3d5de994851c.png">

You can provide your own `FallbackComponent` so this should work:

```js
const App = () => (
  <ErrorBoundary FallbackComponent={() => null}>
    <ChildrenThatCouldThrowEror></ChildrenThatCouldThrowEror>
  </ErrorBoundary>
)
```

**Comment by ThushalIntervest** [comment]
That is really helpful ❤️. Thank You for your quick answer.
