### ISSUE TITLE
I cant see the component boundary

### ISSUE THREAD

**Issue by DwCleb** [carloscuesta/react-native-error-boundary#95]
Hi, I cant see the boundary component when I throw an error.

the throw error: ```throw new Error('💥 CABOOM 💥');```
trigged by onPress

and the only error that show was the react-native error screen.
I was click in dismiss, but the error boundary component not show.

https://user-images.githubusercontent.com/30187750/103559676-6e7e9e80-4eae-11eb-9b64-eb3ad1bdc0cf.mov

**Comment by carloscuesta** [comment]
Hey @DWCleb, can you share a reproduction case with the code to debug what's happening?

Did you try to run the application on release mode to see if the screen appears?

**Comment by DwCleb** [comment]
@carloscuesta This video shows the code in debug mode.
The code implemented is below:
![Screenshot 2021-01-05 at 09 35 04](https://user-images.githubusercontent.com/30187750/103630258-53a53c00-4f39-11eb-8cd8-4a6685a494a6.png)


and I used the onPress to trigged a throw error below
![Screenshot 2021-01-05 at 09 36 36](https://user-images.githubusercontent.com/30187750/103630410-864f3480-4f39-11eb-9fbc-cfcb684c1809.png)


and the behavior was what I reported in the video above

**Comment by carloscuesta** [comment]
The button that that is throwing the error is a children of theErrorBoundary component?

If the answer is yes, seems an issue on the CustomFallback component you're passing

Try to remove the `FallbackComponent` and try again

**Comment by DwCleb** [comment]
Yes, the button is inside <Routes />.
I removed the ```FallbackComponente``` and still not working

**Comment by carloscuesta** [comment]
That's interesting, would you be able to isolate this reproduction case in a demo repository?

If you can't would yo be able to tell me the version of React-Native that you are using?

**Comment by DwCleb** [comment]
I will try isolate it.

the versions below
react version 16.13.1
react native version 0.63.2

**Comment by DwCleb** [comment]
@carloscuesta the error above also happens in this demo: https://github.com/DwCleb/ErrorBoundaryIsolate

The error boundary component doesn't appear

**Comment by carloscuesta** [comment]
Let me take a look @DwCleb

**Comment by carloscuesta** [comment]
I think the problem is the way you're throwing out the Error @DwCleb 

Seems that the simulator on Debug mode when you throw an error like this: 

```js
onClick={() => throw new Error('whatever')}
```

Is being catched by the LogBox and it does not gets into the `ErrorBoundary@componentDidCatch` method. So you'll never see the ErrorBoundary. This only would happen on development, since there's the `react-native` LogBox to show you the error.

Try to throw the error like this:

https://snack.expo.io/@carloscuesta/react-native-error-boundary

![Screenshot 2021-01-05 at 12 38 33](https://user-images.githubusercontent.com/7629661/103642096-fae29d00-4f52-11eb-9e97-c759591cb18a.png)

![Screenshot 2021-01-05 at 12 45 04](https://user-images.githubusercontent.com/7629661/103642710-dcc96c80-4f53-11eb-8261-0573c084bf6f.png)

You'll see the ErrorBoundary component rendered! 🎉 

![2021-01-05 12-46-18 2021-01-05 12_46_32](https://user-images.githubusercontent.com/7629661/103642860-0d110b00-4f54-11eb-9241-dbd83054837f.gif)

**Comment by DwCleb** [comment]
Still not working. 
I cant use the state to show the error component, this is not flow in development.
The goal is catch JS error, and with State I'm forced a component error show, it's a controlled situation, not a real situation of error. 😕

Using state worked, but this not a real case.

I will try some alternatives about JS error and send you the feedback about my solution.

Thank you so much for the help, see you in some hours

**Comment by carloscuesta** [comment]
Hey @DwCleb 

You don't need state to show the ErrorBoundary component. What happens is that on **development mode** some **errors are catched by the LogBox component**

https://reactnative.dev/blog/2020/07/06/version-0.63

So you won't able to render the `ErrorBoundary` component on Development just by throwing an error from the Button.

On **release mode, it will work because the LogBox it's not shipped to your application**, so the component that catches all the JavaScript errors will be the `ErrorBoundary`.

As you say, **you're simulating an error** so that clearly **it's not a real case**. You're trying to force an error to render the ErrorBoundary component on development.

**Comment by DwCleb** [comment]
@carloscuesta  You are right!

Thanks for your support and this clarification.

**Comment by carloscuesta** [comment]
No problem, a pleasure to explain. Thanks to you aswell for creating the demo repository ❤️

Have a great day!

**Comment by mokshmodi96** [comment]
I am using your Library for Error Boundary handling, the fallback component is working okay on the IOS and android in Development mode but whenever i switch to production for android the app crashes immediately. Though the app runs fine on IOS in production mode
